export declare class ReporterEventCommonInfo {
    dev_id: string;
    model: string;
    os_name: string;
    os_ver: string;
    manufacture: string;
    platform: string;
    app_key: string;
    sdk_ver: string;
    bundle_id: string;
    env: string;
    net_type: string;
    user_id?: string;
    constructor(v100: string, w100: string, x100: string, y100: string, z100: string, a101?: string);
}
