export var V2NIMLoginAuthType;
(function (e) {
    e[e["V2NIM_LOGIN_AUTH_TYPE_DEFAULT"] = 0] = "V2NIM_LOGIN_AUTH_TYPE_DEFAULT";
    e[e["V2NIM_LOGIN_AUTH_TYPE_DYNAMIC_TOKEN"] = 1] = "V2NIM_LOGIN_AUTH_TYPE_DYNAMIC_TOKEN";
    e[e["V2NIM_LOGIN_AUTH_TYPE_THIRD_PARTY"] = 2] = "V2NIM_LOGIN_AUTH_TYPE_THIRD_PARTY";
})(V2NIMLoginAuthType || (V2NIMLoginAuthType = {}));
export var V2NIMLoginStatus;
(function (d) {
    d[d["V2NIM_LOGIN_STATUS_LOGOUT"] = 0] = "V2NIM_LOGIN_STATUS_LOGOUT";
    d[d["V2NIM_LOGIN_STATUS_LOGINED"] = 1] = "V2NIM_LOGIN_STATUS_LOGINED";
    d[d["V2NIM_LOGIN_STATUS_LOGINING"] = 2] = "V2NIM_LOGIN_STATUS_LOGINING";
    d[d["V2NIM_LOGIN_STATUS_UNLOGIN"] = 3] = "V2NIM_LOGIN_STATUS_UNLOGIN";
})(V2NIMLoginStatus || (V2NIMLoginStatus = {}));
export var V2NIMLoginClientType;
(function (c) {
    c[c["V2NIM_LOGIN_CLIENT_TYPE_UNKNOWN"] = 0] = "V2NIM_LOGIN_CLIENT_TYPE_UNKNOWN";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_ANDROID"] = 1] = "V2NIM_LOGIN_CLIENT_TYPE_ANDROID";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_IOS"] = 2] = "V2NIM_LOGIN_CLIENT_TYPE_IOS";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_PC"] = 4] = "V2NIM_LOGIN_CLIENT_TYPE_PC";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_WP"] = 8] = "V2NIM_LOGIN_CLIENT_TYPE_WP";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_WEB"] = 16] = "V2NIM_LOGIN_CLIENT_TYPE_WEB";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_RESTFUL"] = 32] = "V2NIM_LOGIN_CLIENT_TYPE_RESTFUL";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_MAC_OS"] = 64] = "V2NIM_LOGIN_CLIENT_TYPE_MAC_OS";
    c[c["V2NIM_LOGIN_CLIENT_TYPE_HARMONY_OS"] = 65] = "V2NIM_LOGIN_CLIENT_TYPE_HARMONY_OS";
})(V2NIMLoginClientType || (V2NIMLoginClientType = {}));
export var V2NIMLoginClientChange;
(function (b) {
    b[b["V2NIM_LOGIN_CLIENT_CHANGE_LIST"] = 1] = "V2NIM_LOGIN_CLIENT_CHANGE_LIST";
    b[b["V2NIM_LOGIN_CLIENT_CHANGE_LOGIN"] = 2] = "V2NIM_LOGIN_CLIENT_CHANGE_LOGIN";
    b[b["V2NIM_LOGIN_CLIENT_CHANGE_LOGOUT"] = 3] = "V2NIM_LOGIN_CLIENT_CHANGE_LOGOUT";
})(V2NIMLoginClientChange || (V2NIMLoginClientChange = {}));
export var V2NIMConnectStatus;
(function (a) {
    a[a["V2NIM_CONNECT_STATUS_DISCONNECTED"] = 0] = "V2NIM_CONNECT_STATUS_DISCONNECTED";
    a[a["V2NIM_CONNECT_STATUS_CONNECTED"] = 1] = "V2NIM_CONNECT_STATUS_CONNECTED";
    a[a["V2NIM_CONNECT_STATUS_CONNECTING"] = 2] = "V2NIM_CONNECT_STATUS_CONNECTING";
    a[a["V2NIM_CONNECT_STATUS_WAITING"] = 3] = "V2NIM_CONNECT_STATUS_WAITING";
})(V2NIMConnectStatus || (V2NIMConnectStatus = {}));
