export var V2NIMChatroomQueueLevelMode;
(function (i) {
    i[i["V2NIM_CHATROOM_QUEUE_LEVEL_MODE_ANY"] = 0] = "V2NIM_CHATROOM_QUEUE_LEVEL_MODE_ANY";
    i[i["V2NIM_CHATROOM_QUEUE_LEVEL_MODE_MANAGER"] = 1] = "V2NIM_CHATROOM_QUEUE_LEVEL_MODE_MANAGER";
})(V2NIMChatroomQueueLevelMode || (V2NIMChatroomQueueLevelMode = {}));
export var V2NIMChatroomKickedReason;
(function (h) {
    h[h["V2NIM_CHATROOM_KICKED_REASON_UNKNOWN"] = -1] = "V2NIM_CHATROOM_KICKED_REASON_UNKNOWN";
    h[h["V2NIM_CHATROOM_KICKED_REASON_CHATROOM_INVALID"] = 1] = "V2NIM_CHATROOM_KICKED_REASON_CHATROOM_INVALID";
    h[h["V2NIM_CHATROOM_KICKED_REASON_BY_MANAGER"] = 2] = "V2NIM_CHATROOM_KICKED_REASON_BY_MANAGER";
    h[h["V2NIM_CHATROOM_KICKED_REASON_BY_CONFLICT_LOGIN"] = 3] = "V2NIM_CHATROOM_KICKED_REASON_BY_CONFLICT_LOGIN";
    h[h["V2NIM_CHATROOM_KICKED_REASON_SILENTLY"] = 4] = "V2NIM_CHATROOM_KICKED_REASON_SILENTLY";
    h[h["V2NIM_CHATROOM_KICKED_REASON_BE_BLOCKED"] = 5] = "V2NIM_CHATROOM_KICKED_REASON_BE_BLOCKED";
})(V2NIMChatroomKickedReason || (V2NIMChatroomKickedReason = {}));
