export var V2NIMChatroomStatus;
(function (k) {
    k[k["V2NIM_CHATROOM_STATUS_DISCONNECTED"] = 0] = "V2NIM_CHATROOM_STATUS_DISCONNECTED";
    k[k["V2NIM_CHATROOM_STATUS_WAITING"] = 1] = "V2NIM_CHATROOM_STATUS_WAITING";
    k[k["V2NIM_CHATROOM_STATUS_CONNECTING"] = 2] = "V2NIM_CHATROOM_STATUS_CONNECTING";
    k[k["V2NIM_CHATROOM_STATUS_CONNECTED"] = 3] = "V2NIM_CHATROOM_STATUS_CONNECTED";
    k[k["V2NIM_CHATROOM_STATUS_ENTERING"] = 4] = "V2NIM_CHATROOM_STATUS_ENTERING";
    k[k["V2NIM_CHATROOM_STATUS_ENTERED"] = 5] = "V2NIM_CHATROOM_STATUS_ENTERED";
    k[k["V2NIM_CHATROOM_STATUS_EXITED"] = 6] = "V2NIM_CHATROOM_STATUS_EXITED";
})(V2NIMChatroomStatus || (V2NIMChatroomStatus = {}));
