export var V2NIMChatroomQueueChangeType;
(function (j) {
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_UNKNOWN"] = 0] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_UNKNOWN";
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_OFFER"] = 1] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_OFFER";
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_POLL"] = 2] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_POLL";
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_DROP"] = 3] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_DROP";
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_PARTCLEAR"] = 4] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_PARTCLEAR";
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_BATCH_UPDATE"] = 5] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_BATCH_UPDATE";
    j[j["V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_BATCH_OFFER"] = 6] = "V2NIM_CHATROOM_QUEUE_CHANGE_TYPE_BATCH_OFFER";
})(V2NIMChatroomQueueChangeType || (V2NIMChatroomQueueChangeType = {}));
