import { CmdConfigMap, CmdMap } from '../../../parser';
import { NIMServiceName } from '../../../sdk/types';
export declare const serviceName: NIMServiceName;
export declare let cmdMap: CmdMap;
export declare const serializeTag: {
    syncPropTag: {
        myInfo: number;
        offlineMsgs: number;
        teams: number;
        roamingMsgs: number;
        relations: number;
        friends: number;
        friendUsers: number;
        msgReceipts: number;
        myTeamMembers: number;
        donnop: number;
        recallMsg: number;
        sessionAck: number;
        broadcastMsgs: number;
        avSignal: number;
        superTeams: number;
        mySuperTeamMembers: number;
        superTeamRoamingMsgs: number;
        deleteSuperTeamMsg: number;
        superTeamSessionAck: number;
        deleteSelfMsgs: number;
        stickTopSessions: number;
        sessionHistoryMsgsDelete: number;
        p2pTeamModifyMessage: number;
        superTeamModifyMessage: number;
        filterMsgs: number;
    };
};
export declare const sessionReliableSyncTag: {
    scene: number;
    sessionId: number;
    syncStatus: number;
    syncEndMsgId: number;
    syncEndMsgidClient: number;
    syncEndMsgTime: number;
    syncStartMsgid: number;
    syncStartMsgidClient: number;
    syncStartMsgTime: number;
    nextMsgid: number;
    nextMsgidClient: number;
    nextMsgTime: number;
    roamMsgSync: number;
    offlineMsgSync: number;
    netCallOfflineMsgSync: number;
};
export declare const cmdConfig: CmdConfigMap;
