export var V2NIMLoginAuthType;
(function (V2NIMLoginAuthType) {
    V2NIMLoginAuthType[V2NIMLoginAuthType["V2NIM_LOGIN_AUTH_TYPE_DEFAULT"] = 0] = "V2NIM_LOGIN_AUTH_TYPE_DEFAULT";
    V2NIMLoginAuthType[V2NIMLoginAuthType["V2NIM_LOGIN_AUTH_TYPE_DYNAMIC_TOKEN"] = 1] = "V2NIM_LOGIN_AUTH_TYPE_DYNAMIC_TOKEN";
    V2NIMLoginAuthType[V2NIMLoginAuthType["V2NIM_LOGIN_AUTH_TYPE_THIRD_PARTY"] = 2] = "V2NIM_LOGIN_AUTH_TYPE_THIRD_PARTY";
})(V2NIMLoginAuthType || (V2NIMLoginAuthType = {}));
export const V2NIMLoginAuthTypeValues = [
    V2NIMLoginAuthType.V2NIM_LOGIN_AUTH_TYPE_DEFAULT,
    V2NIMLoginAuthType.V2NIM_LOGIN_AUTH_TYPE_DYNAMIC_TOKEN,
    V2NIMLoginAuthType.V2NIM_LOGIN_AUTH_TYPE_THIRD_PARTY
];
export var V2NIMLoginStatus;
(function (V2NIMLoginStatus) {
    V2NIMLoginStatus[V2NIMLoginStatus["V2NIM_LOGIN_STATUS_LOGOUT"] = 0] = "V2NIM_LOGIN_STATUS_LOGOUT";
    V2NIMLoginStatus[V2NIMLoginStatus["V2NIM_LOGIN_STATUS_LOGINED"] = 1] = "V2NIM_LOGIN_STATUS_LOGINED";
    V2NIMLoginStatus[V2NIMLoginStatus["V2NIM_LOGIN_STATUS_LOGINING"] = 2] = "V2NIM_LOGIN_STATUS_LOGINING";
    V2NIMLoginStatus[V2NIMLoginStatus["V2NIM_LOGIN_STATUS_UNLOGIN"] = 3] = "V2NIM_LOGIN_STATUS_UNLOGIN";
})(V2NIMLoginStatus || (V2NIMLoginStatus = {}));
export var V2NIMLoginClientType;
(function (V2NIMLoginClientType) {
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_UNKNOWN"] = 0] = "V2NIM_LOGIN_CLIENT_TYPE_UNKNOWN";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_ANDROID"] = 1] = "V2NIM_LOGIN_CLIENT_TYPE_ANDROID";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_IOS"] = 2] = "V2NIM_LOGIN_CLIENT_TYPE_IOS";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_PC"] = 4] = "V2NIM_LOGIN_CLIENT_TYPE_PC";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_WP"] = 8] = "V2NIM_LOGIN_CLIENT_TYPE_WP";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_WEB"] = 16] = "V2NIM_LOGIN_CLIENT_TYPE_WEB";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_RESTFUL"] = 32] = "V2NIM_LOGIN_CLIENT_TYPE_RESTFUL";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_MAC_OS"] = 64] = "V2NIM_LOGIN_CLIENT_TYPE_MAC_OS";
    V2NIMLoginClientType[V2NIMLoginClientType["V2NIM_LOGIN_CLIENT_TYPE_HARMONY"] = 65] = "V2NIM_LOGIN_CLIENT_TYPE_HARMONY";
})(V2NIMLoginClientType || (V2NIMLoginClientType = {}));
export var V2NIMKickedOfflineReason;
(function (V2NIMKickedOfflineReason) {
    V2NIMKickedOfflineReason[V2NIMKickedOfflineReason["V2NIM_KICKED_OFFLINE_REASON_CLIENT_EXCLUSIVE"] = 1] = "V2NIM_KICKED_OFFLINE_REASON_CLIENT_EXCLUSIVE";
    V2NIMKickedOfflineReason[V2NIMKickedOfflineReason["V2NIM_KICKED_OFFLINE_REASON_SERVER"] = 2] = "V2NIM_KICKED_OFFLINE_REASON_SERVER";
    V2NIMKickedOfflineReason[V2NIMKickedOfflineReason["V2NIM_KICKED_OFFLINE_REASON_CLIENT"] = 3] = "V2NIM_KICKED_OFFLINE_REASON_CLIENT";
    V2NIMKickedOfflineReason[V2NIMKickedOfflineReason["V2NIM_KICKED_OFFLINE_REASON_CLIENT_QUIETLY"] = 4] = "V2NIM_KICKED_OFFLINE_REASON_CLIENT_QUIETLY";
})(V2NIMKickedOfflineReason || (V2NIMKickedOfflineReason = {}));
export var V2NIMLoginClientChange;
(function (V2NIMLoginClientChange) {
    V2NIMLoginClientChange[V2NIMLoginClientChange["V2NIM_LOGIN_CLIENT_CHANGE_LIST"] = 1] = "V2NIM_LOGIN_CLIENT_CHANGE_LIST";
    V2NIMLoginClientChange[V2NIMLoginClientChange["V2NIM_LOGIN_CLIENT_CHANGE_LOGIN"] = 2] = "V2NIM_LOGIN_CLIENT_CHANGE_LOGIN";
    V2NIMLoginClientChange[V2NIMLoginClientChange["V2NIM_LOGIN_CLIENT_CHANGE_LOGOUT"] = 3] = "V2NIM_LOGIN_CLIENT_CHANGE_LOGOUT";
})(V2NIMLoginClientChange || (V2NIMLoginClientChange = {}));
export var V2NIMConnectStatus;
(function (V2NIMConnectStatus) {
    V2NIMConnectStatus[V2NIMConnectStatus["V2NIM_CONNECT_STATUS_DISCONNECTED"] = 0] = "V2NIM_CONNECT_STATUS_DISCONNECTED";
    V2NIMConnectStatus[V2NIMConnectStatus["V2NIM_CONNECT_STATUS_CONNECTED"] = 1] = "V2NIM_CONNECT_STATUS_CONNECTED";
    V2NIMConnectStatus[V2NIMConnectStatus["V2NIM_CONNECT_STATUS_CONNECTING"] = 2] = "V2NIM_CONNECT_STATUS_CONNECTING";
    V2NIMConnectStatus[V2NIMConnectStatus["V2NIM_CONNECT_STATUS_WAITING"] = 3] = "V2NIM_CONNECT_STATUS_WAITING";
})(V2NIMConnectStatus || (V2NIMConnectStatus = {}));
