export var V2NIMSignallingChannelType;
(function (V2NIMSignallingChannelType) {
    V2NIMSignallingChannelType[V2NIMSignallingChannelType["V2NIM_SIGNALLING_CHANNEL_TYPE_AUDIO"] = 1] = "V2NIM_SIGNALLING_CHANNEL_TYPE_AUDIO";
    V2NIMSignallingChannelType[V2NIMSignallingChannelType["V2NIM_SIGNALLING_CHANNEL_TYPE_VIDEO"] = 2] = "V2NIM_SIGNALLING_CHANNEL_TYPE_VIDEO";
    V2NIMSignallingChannelType[V2NIMSignallingChannelType["V2NIM_SIGNALLING_CHANNEL_TYPE_CUSTOM"] = 3] = "V2NIM_SIGNALLING_CHANNEL_TYPE_CUSTOM";
})(V2NIMSignallingChannelType || (V2NIMSignallingChannelType = {}));
export var V2NIMSignallingEventType;
(function (V2NIMSignallingEventType) {
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_UNKNOWN"] = 0] = "V2NIM_SIGNALLING_EVENT_TYPE_UNKNOWN";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_CLOSE"] = 1] = "V2NIM_SIGNALLING_EVENT_TYPE_CLOSE";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_JOIN"] = 2] = "V2NIM_SIGNALLING_EVENT_TYPE_JOIN";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_INVITE"] = 3] = "V2NIM_SIGNALLING_EVENT_TYPE_INVITE";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_CANCEL_INVITE"] = 4] = "V2NIM_SIGNALLING_EVENT_TYPE_CANCEL_INVITE";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_REJECT"] = 5] = "V2NIM_SIGNALLING_EVENT_TYPE_REJECT";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_ACCEPT"] = 6] = "V2NIM_SIGNALLING_EVENT_TYPE_ACCEPT";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_LEAVE"] = 7] = "V2NIM_SIGNALLING_EVENT_TYPE_LEAVE";
    V2NIMSignallingEventType[V2NIMSignallingEventType["V2NIM_SIGNALLING_EVENT_TYPE_CONTROL"] = 8] = "V2NIM_SIGNALLING_EVENT_TYPE_CONTROL";
})(V2NIMSignallingEventType || (V2NIMSignallingEventType = {}));
